apiVersion: v2
name: argo-cd
description: "Wrapper chart for installing crossplane and the ionoscloud crossplane provider"
version: 1.0.0
dependencies:
  - name: crossplane
    version: 1.15.2
    repository: https://charts.crossplane.io/stable